"""empty message

Revision ID: 340912c24720
Revises: e31fee066470
Create Date: 2018-08-13 13:03:37.496887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340912c24720'
down_revision = 'e31fee066470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('param',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('value', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'input', sa.Column('params', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'input', 'param', ['params'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'input', type_='foreignkey')
    op.drop_column(u'input', 'params')
    op.drop_table('param')
    # ### end Alembic commands ###
