"""empty message

Revision ID: a65bf6c9a4f9
Revises: 
Create Date: 2018-08-07 15:56:24.861666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65bf6c9a4f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('type', sa.String(length=140), nullable=True),
    sa.Column('value', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domen', sa.String(length=140), nullable=True),
    sa.Column('wap', sa.String(length=140), nullable=True),
    sa.Column('web', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domen')
    )
    op.create_table('list_form',
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('wap', sa.String(length=140), nullable=True),
    sa.Column('web', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('surf_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_url', sa.String(length=256), nullable=True),
    sa.Column('tds_url', sa.String(length=256), nullable=True),
    sa.Column('traffic_type', sa.String(length=3), nullable=True),
    sa.Column('email_type', sa.String(length=3), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['input_id'], ['input.id'], ),
    sa.PrimaryKeyConstraint('input_id', 'form_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('surf_task')
    op.drop_table('list_form')
    op.drop_table('inventory')
    op.drop_table('input')
    op.drop_table('form')
    # ### end Alembic commands ###
