"""empty message

Revision ID: e31fee066470
Revises: 2d1d38b16d64
Create Date: 2018-08-09 18:42:44.827074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31fee066470'
down_revision = '2d1d38b16d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xpath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xpath', sa.String(length=140), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xpath')
    # ### end Alembic commands ###
